curriculum/urls.py
from django.conf.urls import url
from . import views

app_name = 'curriculum'

urlpatterns = [
    # /curriculum/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /curriculum/table/
    url(r'^table/$', views.TableView.as_view(), name='table'),
    # /curriculum/table/
    url(r'^hierarchy/$', views.HierarchyView.as_view(), name='hierarchy'),
    # /curriculum/123/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /curriculum/offering/add
    url(r'^offering/add/$', views.OfferingCreate.as_view(), name='offering-add'),
    # /curriculum/offering/<id>
    url(r'^offering/(?P<pk>[0-9]+)/$', views.OfferingUpdate.as_view(), name='offering-update'),
    # /curriculum/offering/<id>/delete
    url(r'^offering/(?P<pk>[0-9]+)/delete/$', views.OfferingDelete.as_view(), name='offering-delete'),
    # /curriculum/offering/<id>/marketing
    url(r'^offering/(?P<pk>[0-9]+)/marketing/$', views.MarketingUpdate.as_view(), name='marketing-update'),
]

planr/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from curriculum import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^curriculum/', include('curriculum.urls')),
    url(r'^search/$', views.search_lars, name='search'),
]

curriculum/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.db.models import Q
from django.core.urlresolvers import reverse

class Lars(models.Model):
    qual_aim = models.CharField(max_length=10, primary_key=True)
    qual_aim_title = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural = "LARS Entries"
    def __str__(self):
        return self.qual_aim + ' ' + self.qual_aim_title

class OldOffering(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_code = models.CharField(max_length=20, blank=True)
    course_name = models.CharField(max_length=200, help_text="Enter a name that makes sense")

class Offering(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_rpt = models.BooleanField(default=False)
    course_caution = models.BooleanField("Subject to change?", default=False, )
    course_complete = models.BooleanField(default=False)
    course_code = models.CharField(max_length=20, default="to be assigned")
    course_code_old = models.CharField(max_length=20, blank=True)
    course_name = models.CharField(max_length=200, help_text="Please follow syntax: [Subject][Qualification][Level][(Extra Information)]. E.g. Plumbing Diploma L3 (Day Release)")
    DELIVERY_CHOICES = (
        ('FT', 'Full Time'),
        ('PTQ', 'Part Time Qualification'),
        ('HE', 'Higher Education'),
        ('L2L', 'Love2Learn'),
        ('APP', 'Apprenticeship'),
        )
    course_delivery = models.CharField(max_length=100, choices=DELIVERY_CHOICES, default='FT')
    TYPE_CHOICES = (
        ('M', 'Main Aim'),
        ('N', 'Nested Qualification'),
        ('C', 'Child Code'),
        ('S', 'Standalone Course'),
        ('F', 'Functional Skills'),
        ('G', 'Group Code'),
        ('R', 'Register Code'),
        )
    course_type = models.CharField(max_length=100, choices=TYPE_CHOICES, default='M')
    parent_code = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    STRAND_CHOICES = (
        ('A2H', 'Access to HE'),
        ('ACC', 'Accommodation'),
        ('AHC', 'Animal Care'),
        ('APP', 'Apprenticeships'),
        ('ART', 'Arts'),
        ('ASC', 'Ascentis'),
        ('BEA', 'Beauty'),
        ('BER', 'Business Employer Responsive'),
        ('BLS', 'Building Services Engineering'),
        ('BRI', 'Bricklaying'),
        ('BUS', 'Business'),
        ('CAD', 'Careers Advice & Guidance'),
        ('CAR', 'Care'),
        ('CON', 'Construction (Somer Valley)'),
        ('CPT', 'Carpentry'),
        ('CST', 'Construction  CIBE'),
        ('CVC', 'Cardiff and Vale College'),
        ('DEU', 'Distance Education'),
        ('DLH', 'Distance Learning (Highways/ILM)'),
        ('DNG', 'Design'),
        ('DWA', 'Development Worker A'),
        ('ELI', 'Electrical'),
        ('ELS', 'English Language School (inc. ESOL)'),
        ('ELY', 'Early Years'),
        ('ENG', 'Engineering'),
        ('EXM', 'Exam Resiit Fees'),
        ('FDN', 'Foundation Learning'),
        ('FIN', 'Finance'),
        ('FLO', 'Floristry'),
        ('GCS', 'GCSEs'),
        ('HAB', 'Hair & Beauty'),
        ('HAI', 'Hair'),
        ('HOR', 'Horticulture'),
        ('HOS', 'Hospitality'),
        ('INT', 'Information Technology'),
        ('LCV', 'Learning Curve'),
        ('MED', 'Media'),
        ('MFL', 'Modern Foreign Languages'),
        ('MOT', 'Motor Vehicle'),
        ('MRK', 'Marketing'),
        ('MTD', 'Business Professional'),
        ('MUS', 'Music'),
        ('NCC', 'NCC Skills Ltd'),
        ('NGT', 'N-Gaged Training'),
        ('ODC', 'One Day Course'),
        ('OTH', 'Other Miscellaneous Codes'),
        ('PAD', 'Painting & Decorating'),
        ('PAR', 'Performing Arts'),
        ('PBS', 'Public Services'),
        ('PMB', 'Plumbing'),
        ('PRE', 'Pre-16'),
        ('PRM', 'Premier'),
        ('REF', 'Refrigeration'),
        ('SAA', 'Strand Area A'),
        ('SAB', 'Strand Area B'),
        ('SAC', 'Student Advice Centre'),
        ('SFL', 'Skills for Life'),
        ('SHC', 'Short Courses'),
        ('SPO', 'Sport'),
        ('STO', 'Stonemasonry'),
        ('T2G', 'Train to Gain'),
        ('TAS', 'Teaching Assistants'),
        ('TNT', 'Travel & Tourism'),
        ('TRP', 'Traineeship'),
        ('TTR', 'Teacher Training'),
        ('UFU', 'Units for the Unemployed'),
        ('UOB', 'UoB International Foundation Year'),
        ('UOL', 'UoL BSC Business'),
        ('VAP', 'Vocational Access Programme'),
        ('VET', 'Veterinary Nursing'),
        ('XLR', 'Pre-16'),
        )
    strand = models.CharField(max_length=100, choices=STRAND_CHOICES, default='A2H')
    DEPT_CHOICES = (
        ('DACL', 'Dept of Adult and Community Learning'),
        ('DCAE', 'Dept of Creative Arts and Enterprise'),
        ('DEAM', 'Dept of English & Maths'),
        ('DECC', 'Dept of Technology'),
        ('DFDN', 'Dept of Foundation Learning'),
        ('DHBS', 'Dept of Hospitality, Hair, Beauty and Spa Industries'),
        ('DINT', 'Dept for International Studies'),
        ('DLBS', 'Dept of Land Based Studies'),
        ('DSLC', 'Dept of Sport, Leisure & Care'),
        ('DSTB', 'Dept of Services to Business & Work Based Learning'),
        ('DXDY', 'Dept of Specialist Delivery'),
        ('MISC', 'Miscellaneous Codes & Fees (Agresso)'),
        )
    department = models.CharField(max_length=100, choices=DEPT_CHOICES, default='DACL')
    SITE_CHOICES = (
        ('CC','Bath - City Centre Campus'),
        ('SV','Radstock - Somer Valley Campus'),
        ('XX','Cross-College'),
        ('EE','External / Employer'),
        )
    location = models.CharField(max_length=100, choices=SITE_CHOICES, default='CC')
    qual_aim = models.CharField(max_length=10, null=True)
    qual_aim_title = models.ForeignKey(Lars, null=True, blank=True, on_delete=models.SET_NULL)
    fee_comments = models.CharField(blank=True, null=True, max_length=250)
    start_date = models.DateField(auto_now=False, auto_now_add=False, default="2018-08-01")
    end_date = models.DateField(auto_now=False, auto_now_add=False, default="2019-06-30")
    start_time = models.TimeField(auto_now=False, auto_now_add=False, null=True, default="09:00")
    end_time = models.TimeField(auto_now=False, auto_now_add=False, null=True, default="16:30")
    DAY_CHOICES = (
        ('Various', 'Multiple Days'),
        ('Weds/Thurs/Fri', 'Weds/Thurs/Fri'),
        ('Weds/Fri', 'Weds/Fri'),
        ('Wednesday', 'Wednesday'),
        ('Wed/Thurs', 'Wed/Thurs'),
        ('Tuesday', 'Tuesday'),
        ('Tues/Wed/Thurs/Fri', 'Tues/Wed/Thurs/Fri'),
        ('Tues/Wed/Thurs', 'Tues/Wed/Thurs'),
        ('Tues/Wed', 'Tues/Wed'),
        ('Tues/Thurs', 'Tues/Thurs'),
        ('Tues/Fri', 'Tues/Fri'),
        ('Thursday', 'Thursday'),
        ('Thurs/Sat', 'Thurs/Sat'),
        ('Thurs/Fri', 'Thurs/Fri'),
        ('Sunday', 'Sunday'),
        ('Saturday', 'Saturday'),
        ('Mon-Fri', 'Mon-Fri'),
        ('Monday', 'Monday'),
        ('Mon/Wed', 'Mon/Wed'),
        ('Mon/Tues/Wed/Thurs', 'Mon/Tues/Wed/Thurs'),
        ('Mon/Tues/Fri', 'Mon/Tues/Fri'),
        ('Mon/Tues', 'Mon/Tues'),
        ('Mon/Thurs', 'Mon/Thurs'),
        ('Mon/Fri', 'Mon/Fri'),
        ('Friday', 'Friday'),
        )
    day = models.CharField(max_length=100, choices=DAY_CHOICES, default='Various', help_text="Day or days that course regularly runs. If combination is not in list, use 'Multiple Days' or contact CIS to have it added to the list.")
    study_year = models.IntegerField(default=1, help_text="For courses with a duration of one year or less, this will always be '1'")
    study_year_duration = models.IntegerField(default=1, help_text="How many years will this course take overall?")
    wk_hrs = models.IntegerField(default=0, help_text="How many hours of study per week?")
    number_wks = models.IntegerField(default=0, help_text="How many weeks will this course run for?")
    glh = models.IntegerField(default=0, help_text="Total guided learning hours, including teaching and tutorials; does NOT include employability")
    number_grps = models.IntegerField(default=1, help_text="How many groups will the course need?")
    min_students = models.IntegerField(default=5, help_text="Minimum number of students required for course to run / be financially viable")
    max_students = models.IntegerField(default=0, help_text="Maximum number of students that can be taught - total, not per group")
    tuition_fee = models.IntegerField(default=0, null=True, blank=True)
    tuition_fee_old = models.IntegerField(default=0, null=True, blank=True)
    exam_fee = models.IntegerField(default=0, null=True, blank=True)
    exam_fee_old = models.IntegerField(default=0, null=True, blank=True)
    materials_fee = models.IntegerField(default=0, null=True, blank=True)
    materials_fee_old = models.IntegerField(default=0, null=True, blank=True)
    other_fee = models.IntegerField(default=0, null=True, blank=True)
    other_fee_old = models.IntegerField(default=0, null=True, blank=True)
    fcr_fee = models.IntegerField(default=0, null=True, blank=True)
    fcr_fee_old = models.IntegerField(default=0, null=True, blank=True)
    weighted_matrix = models.IntegerField(default=0, null=True, blank=True)
    mkt_course_name = models.CharField(default="", max_length=250, help_text="A shorter, easily understood title suitable for print and web, avoid technical language and abbreviations")
    mkt_course_overview = models.TextField(default="", help_text="A general overview of the qualification or course")
    PROSPECTUS_CHOICES = (
        ('NONE','None (do not advertise)'),
        ('FT','Full Time Prospectus'),
        ('PT','Part Time / Love2Learn Prospectus'),
        ('AP','Apprenticeship Prospectus'),
        ('FTAP','Full Time and Apprenticeship'),
        ('PTAP','Part Time and Apprenticeship'),
        ('FTPT','Full Time and Part Time'),

curriculum/views.py
from django.views import generic
from .models import Offering, Lars
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.db.models import Q
from django.shortcuts import render_to_response

class IndexView(generic.ListView):
    template_name = 'curriculum/index.html'

    def get_queryset(self):
        return Offering.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        context['drafts'] = self.get_queryset().filter(course_caution=True)
        context['commits'] = self.get_queryset().filter(course_caution=False)

        return context

class TableView(generic.ListView):
    template_name = 'curriculum/table.html'

    def get_queryset(self):
        return Offering.objects.all()

class HierarchyView(generic.ListView):
    template_name = 'curriculum/hierarchy.html'

    def get_queryset(self):
        return Offering.objects.all()

    def get_context_data(self, **kwargs):
        context = super(HierarchyView, self).get_context_data(**kwargs)
        context['main'] = self.get_queryset().filter(course_type='M')
        context['sub'] = self.get_queryset().filter(parent_code__in=context['main'])
        return context

class DetailView(generic.DetailView):
    model = Offering
    template_name = 'curriculum/detail.html'

class OfferingCreate(CreateView):
    model = Offering
    template_name = 'curriculum/add-form.html'
    fields = ['course_caution','course_name','course_delivery','course_type','parent_code','strand','department','location','qual_aim','fee_comments','start_date','end_date','start_time','end_time','day','study_year','study_year_duration','wk_hrs','number_wks','glh','number_grps','min_students','max_students','mkt_course_name','mkt_course_overview','mkt_prospectus','mkt_entry_req','mkt_topics','mkt_target','mkt_learning','mkt_assess','mkt_career','mkt_add_costs','mkt_where','mkt_bring','mkt_other','mkt_tutor',]

class OfferingUpdate(UpdateView):
    model = Offering
    template_name = 'curriculum/edit-form.html'
    fields = ['course_caution','course_name','course_delivery','course_type','parent_code','strand','department','location','qual_aim','fee_comments','start_date','end_date','start_time','end_time','day','study_year','study_year_duration','wk_hrs','number_wks','glh','number_grps','min_students','max_students','mkt_course_name','mkt_course_overview','mkt_prospectus','mkt_entry_req','mkt_topics','mkt_target','mkt_learning','mkt_assess','mkt_career','mkt_add_costs','mkt_where','mkt_bring','mkt_other','mkt_tutor',]

class MarketingUpdate(UpdateView):
    model = Offering
    fields = ['mkt_course_name','mkt_course_overview','mkt_prospectus','mkt_entry_req','mkt_topics','mkt_target','mkt_learning','mkt_assess','mkt_career','mkt_funding','mkt_add_costs','mkt_where','mkt_bring','mkt_other','mkt_tutor',]

class OfferingDelete(DeleteView):
    model = Offering
    success_url = reverse_lazy('curriculum:table')

def search_lars(request):
    if request.method == "POST":
        search_text = request.POST['search_text']
    else:
        search_text = ''

    if search_text == '':
        result = ''
    else:
        result = Lars.objects.filter(qual_aim__icontains=search_text)[:3]

    return render_to_response('curriculum/ajax_search.html', {'lars': result})

curriculum/templates/curriculum/ajax_search.html
{% if lars.count > 0 %}

<a onclick="clearSearch()"><span style="color: red" class="pull-right">close search x</span></a>
<br>
{% for lars in lars %}
  <span>
    <strong>Qual Aim:</strong> {{ lars.qual_aim }}</br>
    <strong>Qual Title:</strong> {{ lars.qual_aim_title }}<br>
    <strong>Qual Level:</strong> Level 3<br>
    <strong>Awarding Body:</strong> EDEXCEL<br>
    <strong>GLH Min/Max:</strong> 350/540<br>
    <strong><a href="" onclick="copyQual({{ lars.qual_aim }}); return false">Copy Qual Aim</a></strong>
  </span><br><br>
{% endfor %}

{% else %}
<span>Nothing to show!</span>
{% endif %}

curriculum/templates/curriculum/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Planr{% endblock %}</title>
  <!-- Loads the path to your static files -->
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'curriculum/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

</head>

<body>
  <div class="container-fluid">
    <div class="panel panel-default" style="display: inline-block">
      <div class="panel-heading">
      <h3>Hi {{ request.user.first_name }}! Here are the courses in your department</h3>
      <div>
      <div style="display: inline"><button class="btn btn-primary">Repeat an Old Course</button></div>
      <div style="display: inline"><button class="btn btn-primary" onclick="location.href='{% url 'curriculum:offering-add' %}'">Create a New Course</button></div>
      <div style="display: inline"><button class="btn btn-info" onclick="location.href='{% url 'curriculum:hierarchy' %}'">Hierarchy View</button></div>
      <div style="display: inline"><button class="btn btn-info" onclick="location.href='{% url 'curriculum:table' %}'">Table View</button></div>
      <div style="display: inline"><button class="btn btn-info" onclick="location.href='{% url 'curriculum:index' %}'">Summary View</button></div>
      <div style="display: inline"><button class="btn btn-success" onclick="location.href='https://github.com/lb13/planr/blob/master/introduction.md'">User Guide</button></div>
    </div><br>
    </div>
      <div class="panel-body">
{% block body %}
{% endblock %}
<div class="panel-footer">
<div style="display: inline">&copy; Bath College | 2017</div>
<div style="display: inline" class="pull-right"><a href="https://github.com/lb13/planr">
  <img style="height: 24px" src="{% static 'curriculum/images/github.svg' %}">
  &nbsp;&nbsp;read the docs here</a></div>
  </div>
</div>
</div>
</div>

<script type="text/javascript" src="{% static 'curriculum/custom.js' %}"></script>
<script type="text/javascript" src="{% static 'curriculum/ajax.js' %}"></script>
<script type="text/javascript" src="{% static 'curriculum/tablesorter.js' %}"></script>
<script>
$("#myTable tr").click(function() {
    var selected = $(this).hasClass("highlight");
    $("#myTable tr").removeClass("highlight");
    if(!selected)
            $(this).addClass("highlight");
});

function saveDraft(){
  var inputs = document.getElementsByTagName('input');
  var textareas = document.getElementsByTagName('textarea');
  for (var i = 0; i < inputs.length; i += 1) {
      if (inputs[i].value == '') {
        inputs[i].value = 'tbc';
      }
    }
  for (var i = 0; i < textareas.length; i += 1) {
      if (textareas[i].value == '') {
        textareas[i].value = 'tbc';
      }
    }
  document.getElementById("id_course_caution").checked = true;
  document.getElementById("addOffering").submit();
  }

function copyQual(x){
  document.getElementById('id_qual_aim').value = x;
}
</script>
</body>
</html>

curriculum/templates/curriculum/detail.html
{% extends 'curriculum/base.html' %}

{% block body %}
<div class="container">
  <div class="panel col-sm-6">
  <div class="panel-body">
    Confirmed offering.
<h3>Name: {{ offering.course_name }}</h3>
<h4>Code: {{ offering.course_code }}</h4>
<a href="/">back to the plan!</a>
</div>
</div>
</div>
{% endblock %}

curriculum/templates/curriculum/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-3">{{ field.label_tag }}</label>
    <div class="col-sm-9">{{ field }}</div>
  </div>
{% endfor %}

curriculum/templates/curriculum/hierarchy.html
{% extends 'curriculum/base.html' %}

{% block body %}
{% if object_list %}
<div class="container">
  <div class="col-sm-4">
    <h2>Main Aims</h2>
  </div>
  <div class="col-sm-4">
    <h2>Child / Nested Aims</h2>
  </div>
</div>
<br>
{% for mainoffering in main %}
<div class="container" style="margin-bottom: 25px" id="{{ mainoffering.course_id }}">
  <div class="col-sm-4" style="background-color: #66a266; padding: 5px; border-radius: 5px">{{ mainoffering.course_name }} - {{ mainoffering.course_code }}</div>
  <div class="col-sm-4">
  {% for offering in sub %}
    {% if offering.parent_code == mainoffering %}
      <div style="background-color: #95c195; padding: 5px; border-radius: 5px" id="{{ offering.course_id }}">{{ offering.course_name }} - {{ offering.course_code }}</div>
    {% endif %}
  {% endfor %}
<a onclick="toggle('{{ mainoffering.course_id }}list')"><span class="glyphicon glyphicon-plus"></span> Add Child/Nested</a>
<div id="{{ mainoffering.course_id }}list" style="display: none">aklsdjaslkdj</div>
</div>
  </div>
{% endfor %}

{% else %}
  <h3>There are no courses in your curriculum yet!</h3>
{% endif %}
</div>

{% endblock %}

curriculum/templates/curriculum/index.html
{% extends 'curriculum/base.html' %}

{% block body %}
{% if object_list %}
<input type="search" style="width: 100%" class="light-table-filter" data-table="order-table" placeholder="Quick filter">

<div class="col-md-5">
<table class="table order-table tablesorter">
    <thead><tr><th>Draft Offerings</th></tr></thead>
    <tbody>
{% for offering in drafts %}
  <tr>
    <td>{{ offering.course_name }} | {{ offering.qual_aim }} ({{ offering.qual_aim_title }})</td>
    <td><a href="#"><span style="color: green" class="glyphicon glyphicon-pencil"></span></a></td>
    <td><a href="#"><span style="color: red" class="glyphicon glyphicon-trash"></span></a></td>
  </tr>
{% endfor %}
</tbody>
</table>
  </div>
<div class="col-md-5 col-md-offset-2">
  <table class="table order-table tablesorter">
      <thead><tr><th>Committed Offerings</th></tr></thead>
      <tbody>
  {% for offering in commits %}
    <tr>
      <td>{{ offering.course_name }} | {{ offering.qual_aim }} ({{ offering.qual_aim_title }})</td>
      <td><a href="#"><span style="color: green" class="glyphicon glyphicon-pencil"></span></a></td>
    </tr>
  {% endfor %}
</tbody>
</table>
</div>
{% else %}
  <h3>There are no courses in your curriculum yet!</h3>
{% endif %}
</div>

{% endblock %}

curriculum/templates/curriculum/offering_form.html
{% extends 'curriculum/base.html' %}
{% block title %}{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-body">

          <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            {% include 'curriculum/form-template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Save</button>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

curriculum/templates/curriculum/search.html
<form method="GET" action="">
  <input type="text" name="q" placeholder="search quals"/>
  <input type="submit" value="search"/>
</form>